In [17]:
import numpy as np

In [3]:
my_list = [1, 2, 3]
x = np.array(my_list)
type(x)

numpy.ndarray

In [4]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [6]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [7]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [8]:
random_array = np.random.randint(0,50,10)
random_array_max = random_array.max()
random_array_min = random_array.min()
random_array_max_index = random_array.argmax()
random_array_max_index

2

In [9]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [10]:
arr.shape

(25,)

In [11]:
array_of_zeros = np.zeros(10)
array_of_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
array_of_ones = np.ones(10)
array_of_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
array_of_tens = np.ones(10) * 10
array_of_tens

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [15]:
arr_1 = np.random.randint(10,51, 40)
arr_1

array([47, 26, 29, 44, 40, 25, 18, 46, 10, 36, 23, 27, 34, 18, 13, 30, 24,
       32, 13, 27, 45, 38, 40, 47, 34, 13, 11, 47, 22, 14, 25, 29, 37, 39,
       40, 43, 12, 13, 22, 24])

In [18]:
arr_1_even = np.arange(10,51,2)
arr_1_even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [19]:
arr_3 = np.arange(0,9).reshape(3,3)
arr_3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])