In [3]:
import numpy as np

In [4]:
my_list = [1, 2, 3]
x = np.array(my_list)
type(x)

numpy.ndarray

In [5]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [7]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [8]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [9]:
random_array = np.random.randint(0,50,10)
random_array_max = random_array.max()
random_array_min = random_array.min()
random_array_max_index = random_array.argmax()
random_array_max_index

0

In [10]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [11]:
arr.shape

(25,)

In [12]:
array_of_zeros = np.zeros(10)
array_of_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
array_of_ones = np.ones(10)
array_of_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
array_of_tens = np.ones(10) * 10
array_of_tens

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [15]:
arr_1 = np.random.randint(10,51, 40)
arr_1

array([15, 30, 16, 22, 36, 27, 37, 48, 16, 48, 48, 41, 37, 18, 27, 24, 18,
       35, 25, 30, 25, 44, 40, 35, 43, 37, 19, 10, 49, 30, 14, 26, 13, 11,
       25, 17, 20, 14, 45, 24])

In [16]:
arr_1_even = np.arange(10,51,2)
arr_1_even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [17]:
arr_3 = np.arange(0,9).reshape(3,3)
arr_3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
arr_identity_matrix = np.eye(3)
arr_identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
#generate random number between 0 and 1
arry_random_1 = np.random.rand(1)
arry_random_1

array([0.34214149])

In [20]:
# Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
arry_random_2 = np.random.randn(25)
arry_random_2

array([ 0.75135236, -0.1394322 ,  0.73183282,  2.26905422, -0.85494633,
       -1.44564103, -1.290186  , -2.27298711, -0.7909116 ,  0.04318447,
       -1.00724398,  0.60913575, -2.04282966,  0.72279222, -0.9111329 ,
        0.83632691, -1.45148942, -0.48669426,  0.14010482,  0.80122004,
       -0.64650303,  0.87051038,  1.25639357,  1.59172247, -0.28505834])

In [22]:
arr_4 = np.zeros(100).reshape(10,10) + 0.01
arr_4

array([[0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]])