In [2]:
import numpy as np

In [3]:
my_list = [1, 2, 3]
x = np.array(my_list)
type(x)

numpy.ndarray

In [4]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [6]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [7]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [8]:
random_array = np.random.randint(0,50,10)
random_array

array([30, 20, 36, 10, 31, 10,  8,  2, 24, 37])

In [9]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])